version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: api
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./schedule/data/:/api/schedule/data/
    networks:
      - canary-network   

  update-api:
    build: 
      context: ./schedule
      dockerfile: ./Dockerfile
    env_file: .env
    container_name: update-api
    ports:
      - 8001:8001
    restart: unless-stopped
    volumes:
      - ./schedule/data/:/schedule/data/  
    networks:
      - canary-network     

networks:
  canary-network:
    driver: bridge

