version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: img-medano-api  
    container_name: medano-api
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./schedule/data/:/api/schedule/data/
    networks:
      - medano-network   

  update-api:
    build: 
      context: ./schedule
      dockerfile: ./Dockerfile
    image: img-medano-update-api  
    container_name: medano-update-api
    ports:
      - 8001:8001
    restart: unless-stopped
    volumes:
      - ./schedule/data/:/schedule/data/  
    networks:
      - medano-network     

networks:
  medano-network:
    driver: bridge

